spring:
#  rabbitmq:
#    username: sunzg
#    password: zhaoguo
#    virtual-host: /
#    host: 82.156.13.69
#    port: 35672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: ENC(2g3VSrP4AkHgTWQCDq5yDjiNl3ukuK3sOwjju/wo3Gs=)
      url: ENC(P5LYkvV7GYgzhuEvOmwcoADJGS0EKmRca/kVUx9lzFNqAsZ05vJ2lyuI2/BdlF+6nV5HV+WAWck=)
      username: ENC(wmGVdm3W47nLS2MdPwsVgDTStCkLk/sl)
      password: ENC(wmGVdm3W47nLS2MdPwsVgDTStCkLk/sl)

  redis:
    host: 82.156.13.69
    port: 16379
    password: 123456
    timeout: 10s
    database: 0
    lettuce:
      # 关闭超时时间
      shutdown-timeout: 1s
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池中的最大空闲连接 默认 8
        max-idle: 3
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1s
