spring:
#  rabbitmq:
#    username: sunzg
#    password: zhaoguo
#    virtual-host: /
#    host: 82.156.13.69
#    port: 35672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: ENC(2g3VSrP4AkHgTWQCDq5yDjiNl3ukuK3sOwjju/wo3Gs=)
      url: ENC(P5LYkvV7GYgzhuEvOmwcoADJGS0EKmRca/kVUx9lzFNqAsZ05vJ2lyuI2/BdlF+6nV5HV+WAWck=)
      username: ENC(wmGVdm3W47nLS2MdPwsVgDTStCkLk/sl)
      password: ENC(wmGVdm3W47nLS2MdPwsVgDTStCkLk/sl)