spring:
  profiles:
    active:
      - dev
      - doc

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /
  port: 9080
  shutdown: graceful
  http2:
    enabled: true

mybatis-plus:
  type-aliases-package: sun.zhao.guo.model
  global-config:
    banner: false
    db-config:
      id-type: assign_uuid
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

logging:
  level:
    sun.zhao.guo: debug
    org.springframework: warn